# -- Language Configuration --
# https://jpanther.github.io/congo/docs/configuration/#configuration

languageCode = "fr"
languageName = "fr"
languageDirection = "ltr"
weight = 1

title = "Donan"

[params]
  dateFormat = "2 January 2006"
  description = "Donan"

[params.author]
  name = "Donan"
  image = "img/logo.jpg"
  headline = "Lorem Ipsum"
  bio = "Lorem Ispum"
  links = [
    { instagram = "https://instagram.com/donanrobinson"},
    { youtube = "https://www.youtube.com/@Donan.R" },
    { email = "mailto:donanr@gmail.com" },
    { facebook = "https://www.facebook.com/profile.php?id=100010090934730" },
    { tiktok = "https://tiktok.com/@donanrobinson" },
    { spotify = "https://open.spotify.com/intl-fr/artist/0ha4AJZF2T0PDc6scMdSlW?si=DGDgFm7HTfKKfWwKVgC_6g" },
    { apple = "https://music.apple.com/fr/artist/donan/1784738941" }
  ]