[[main]]
  name = "EP"
  pageRef = "ep"
  weight = 1

[[main]]
  name = "Vidéos"
  pageRef = "videos"
  weight = 2

[[main]]
  name = "Concerts"
  pageRef = "concerts"
  weight = 3

[[main]]
  name = "A propos"
  pageRef = "a-propos"
  weight = 4

[[main]]
  name = "Boutique"
  pageRef = "boutique"
  weight = 5

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/donanrobinson"
  weight = 10

[[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://www.youtube.com/@Donan.R"
  weight = 11

[[main]]
  identifier = "spotify"
  pre = "spotify"
  url = "https://open.spotify.com/artist/0ha4AJZF2T0PDc6scMdSlW"
  weight = 12

[[main]]
  identifier = "apple"
  pre = "music"
  url = "https://music.apple.com/fr/artist/donan/1784738941"
  weight = 13

[[footer]]
  name = "Infos du site ℹ️"
  pageRef = "site/infos"
  weight = 1
