# -- Menus Configuration --
# https://jpanther.github.io/congo/docs/configuration/#menus

[[main]]
  name = "clips"
  pageRef = "clips"
  weight = 10

[[main]]
  name = "concerts"
  pageRef = "concerts"
  weight = 30

[[main]]
  name = "photos"
  pageRef = "photos"
  weight = 20

# [[main]]
#   identifier = "search"
#   weight = 99
#   [main.params]
#     action = "search"

# [[main]]
#   identifier = "appearence"
#   weight = 99
#   [main.params]
#     action = "appearance"

# [[main]]
#   identifier = "locale"
#   weight = 100
#   [main.params]
#     action = "locale"